### ISSUE TITLE
doctrine orm:schema-tool:create error

### ISSUE THREAD

**Issue by horllste** [sarhanm/sms-survey#1]
i got stuck when i run

php vendor/bin/doctrine orm:schema-tool:create  --dump-sql

i got a 
C:\Users\self>php vendor/bin/doctrine orm:schema-tool:create -h
Could not open input file: vendor/bin/doctrine

Help will be appreciated.
thanks

**Comment by sarhanm** [comment]
There was a version bump to better pin the correct version of doctrine. I'm not sure if that was your issue. There was also a critical step missing from the readme on how to setup the library if you were using composer. 

As for the doctrine binary missing from your bin directory, i'm not sure if thats a windows only issue or a composer issue. The composer install command should have downloaded all required files.
